commerce/auctions/urls.py
from django.urls import path
from . import views

app_name = "auctions"
urlpatterns = [
    path('', views.auctions_list, name='auctions_list'),
    path('<slug:category_slug>/',
         views.auctions_list,
         name='auctions_list_by_category'),
    path('<int:id>/<slug:slug>',
         views.auction_detail,
         name='auction_detail'),
]

commerce/commerce/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('auctions.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

commerce/auctions/models.py
from django.urls import reverse
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('auctions:auctions_list_by_category',
                       args=[self.slug])


class Auction(models.Model):
    category = models.ForeignKey(Category, related_name='auctions', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='auctions/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    start_price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('auctions:auction_detail',
                       args=[self.id, self.slug])

commerce/auctions/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Auction


def auctions_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    auctions = Auction.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        auctions = auctions.filter(category=category)
    return render(request, 'auctions/auction/list.html',
                  {
                      'category': category,
                      'categories': categories,
                      'auctions': auctions
                  })


def auction_detail(request, id, slug):
    auction = get_object_or_404(Auction,
                                id=id,
                                slug=slug,
                                available=True
                                )
    return render(request, 'auctions/auction/detail.html',
                  {
                      'auction': auction
                  })

commerce/auctions/templates/auctions/auction/detail.html
{% extends "auctions/base.html" %}
{% load static %}

{% block title %}
  {{ auction.name }}
{% endblock %}

{% block content %}
  <div class="auction-detail">
    <h1>{{ auction.name }}</h1>
    <img src="{% if auctions.image %}{{ auctions.image.url }}{% else %}
    {% static "img/no_image.png" %}{% endif %}">
        <h2>
            <a href="{{ auctions.category.get_absolute_url }}">
            {{ auction.category }}
            </a>
        </h2>
      <p class="start_price">${{ auction.start_price }}</p>
    {{ auction.description }}
  </div>
{% endblock %}

commerce/auctions/templates/auctions/auction/list.html
{% extends "auctions/base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }}{% else %}Auctions{% endif %}
{% endblock %}
{% block content %}
    <div id="main" class="auctions-list">
        <h1>{% if category %}{{ category.name }}{% else %}Auctions{% endif %}</h1>
        {% for auction in auctions %}
            <div class="item">
                <a href="{{ auction.get_absolute_url }}">
                    <img src="{% if auctions.image %}{{ auctions.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
                </a><br>
                <a href="{{ auction.get_absolute_url }}">{{ auction.name }}</a><br>
                $ {{ auction.start_price }}
            </div>
        {% endfor %}
    </div>
{% endblock %}

commerce/auctions/templates/auctions/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
            <title>{% block title %}Commerce{% endblock %}</title>
                <link href="{% static 'css/base.css' %}" rel="stylesheet">
    </head>
<body>
    <div id="header">
        <a href="/" class="logo">Commerce</a>
    </div>
    <div id="subheader">
        <div class="favorite">
            Your favorites is empty.
        </div>
    </div>
    <div id="sidebar">
        <h3>Categories</h3>
        <ul>
            <li {% if not category %}class="selected"{% endif %}>
                <a href="{% url 'auctions:auctions_list' %}">All</a>
            </li>
            {% for c in categories %}
            <li {% if category.slug == c.slug %}class="selected"{% endif %}>
                <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
            </li>
            {% endfor %}
        </ul>
    </div>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>